services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aboba


  app:
    build: .
    restart: always
    container_name: web-test
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - aboba

networks:
  aboba:
    driver: bridge

volumes:
  postgres_data: